baseURL = "http://www.plyoung.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "plyoung"
theme = "hello"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
  name = "Leslie Young"

[params]

  [[params.links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/plyoung/"

  #[params.colors]
  #  background = "#81c6ff"
  #  foreground = "#edf7ff"
  #  hover = "#ffba82"    

