baseURL = "http://www.plyoung.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "plyoung"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
  name = "PL Young"

[params]

  [[params.links]]
    icon = "itch-io"
    title = "itch.io"
    url = "https://plyoung.itch.io/"

  [[params.links]]
    icon = "steam"
    title = "Steam"
    url = "https://store.steampowered.com/dev/plyoung"

  [[params.links]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/pl_young"

  [[params.links]]
    icon = "youtube"
    title = "Youtube"
    url = "https://www.youtube.com/channel/UCbrbCz7ZG4zdnB0XjbqdFzA"

  [[params.links]]
    icon = "github"
    title = "Github"
    url = "https://github.com/plyoung/"

  [[params.links]]
    icon = "patreon"
    title = "Patreon"
    url = "https://www.patreon.com/plyoung"

  [params.colors]
    background = "#322a40"
    foreground = "#edf7ff"
    hover = "#ffba82"    

