---
# based on https://themes.gohugo.io/themes/piko/
baseURL: https://www.plyoung.com/
languageCode: en-us
title: PLYOUNG
theme: plyoung_site
paginate: "9"
copyright: # none
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: PLYOUNG
  description: Game developer.
  math: false
  images:
  - "/uploads/og.webp"
  label:
    title: 
    text: 
    backgroundImage: "/uploads/background.webp"    
    lightNavIcon: /uploads/logo.svg
    darkNavIcon: /uploads/logo.svg
    iconHeight: "32"
    iconWIdth: "32"
  comments: false
  mainSections:
  - blog
  ShowShareButtons: false
  ShowCodeCopyButtons: false
  ShowRelated: false
  CookieNotice: We use cookies to improve your experience on this site
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: true
    favicon: /uploads/icon.svg
    favicon16x16: /uploads/icon.svg
    favicon32x32: /uploads/icon.svg
    apple_touch_icon: /uploads/icon.svg
    safari_pinned_tab: /uploads/icon.svg
  ShowReadingTime: false
  ShowBreadCrumbs: false
  homepage:
    # Hero Section
    disableHeroSection: true
    heroUpperTitle: 
    heroTitle: PLYOUNG
    heroDescription: #Game developer
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/background.webp"
    # Blog Section
    disableBlogSection: true
    blogTitle: #Posts
    blogDescription: #Latest posts
    seeMoreText: See more
    # About Section    
    disableAboutSection: true
    aboutTitle: About
    aboutDescription: About me
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: Info info info
    # Portfolio Section
    disablePortfolioSection: false
    portfolioTitle: Games
    portfolioDescription: 
    portfolio:
    - imageUrl: /uploads/logo_slimyharvest.webp
      alt: Slimy Harvest
      description: Slimy Harvest
      websiteUrl: "/game/slimy-harvest"
    - imageUrl: /uploads/logo_rcdash.webp
      alt: RC Dash
      description: RC Dash
      websiteUrl: "/game/rc-dash"      
    - imageUrl: /uploads/logo_infindustry.webp
      alt: Infindustry
      description: Infindustry
      websiteUrl: "/game/infindustry"
    - imageUrl: /uploads/logo_battlemass2.webp
      alt: Battlemass 2
      description: Battlemass 2
      websiteUrl: "/game/battlemass2"
    - imageUrl: /uploads/logo_peterblock.webp
      alt: Peter Block
      description: Peter Block
      websiteUrl: "/game/peter-block"
    - imageUrl: /uploads/logo_ufoz.webp
      alt: Oh my. UFOz!
      description: Oh my. UFOz!
      websiteUrl: "/game/ufoz"
    - imageUrl: /uploads/logo_muchine.webp
      alt: Muchine
      description: Muchine
      websiteUrl: "/game/muchine"
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  # - name: Blog
  #   title: Blog
  #   pre: pen-tool
  #   url: "/blog"
  #   weight: "20"
  # - name: Search
  #   title: Search
  #   pre: search
  #   url: "/search"
  #   weight: "30"
  - name: Games
    title: Games
    pre: "fa-solid fa-gamepad"
    url: "/"
    weight: "1" 
  - name: Contact
    title: Contact
    pre: "fa-solid fa-envelope"
    url: "/contact/"
    weight: "2"
  - name: " " 
    title: 
    pre: 
    url: 
    weight: "9"     
  - name: PLYoung on Itch.io
    title: 
    pre: "fa-brands fa-itch-io"
    url: "https://plyoung.itch.io/"
    params:
      rel: external
    weight: "10"
  - name: PLYoung on Steam
    title: 
    pre: "fa-brands fa-steam"
    url: "https://store.steampowered.com/dev/plyoung"
    params:
      rel: external
    weight: "11"
  - name: Follow PLYoung on Twitter
    title: 
    pre: "fa-brands fa-twitter"
    url: "https://twitter.com/pl_young"
    params:
      rel: external
    weight: "20"
  - name: PLYoung's YouTube channel
    title: 
    pre: "fa-brands fa-youtube"
    url: "https://www.youtube.com/@plyoung"
    params:
      rel: external
    weight: "21"
  - name: PLYoung's Github repos
    title: 
    pre: "fa-brands fa-github"
    url: "https://github.com/plyoung/"
    params:
      rel: external
    weight: "30"    
  # search: # Search page's quick links
  # - name: Categories
  #   title: Categories
  #   url: "/categories"
  #   weight: "10"
  # - name: Archives
  #   title: Archives
  #   url: "/archives"
  #   weight: "20"
  # - name: Tags
  #   title: Tags
  #   url: "/tags"
  #   weight: "30"
